name: Validate Gitflow and Semantic Versioning

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Gitflow Branch Naming
        id: gitflow
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" =~ ^(feature|release|hotfix|bugfix)\/.+$ ]]; then
            echo "Branch name is valid according to Gitflow."
          else
            echo "Invalid branch name. Must follow Gitflow naming conventions."
            exit 1
          fi

      - name: Success Message
        run: echo "All validations passed!"
